### ISSUE TITLE
后端可以运行吗？

### ISSUE THREAD

**Issue by leruge** [suanju/im-qinyu#1]
搭建后无法访问呀，全是500

**Comment by suanju** [comment]
注意配置文件哦！

**Comment by leruge** [comment]
配置文件不是只有数据库么？还需要配置什么吗、

**Comment by suanju** [comment]
调试打开，你看一下具体报错信息

**Comment by leruge** [comment]
没有访问到tp框架，访问index.php文件直接报500，我再搭建一下。

**Comment by suanju** [comment]
给报错图才能具体看看

**Comment by leruge** [comment]
我什么都不配置和数据库配置正确报一样的错误，访问不到tp里面。
![1](https://github.com/suanju/im-qinyu/assets/33196309/c9fe3853-864d-466c-bdf3-c925aeb275e3)

**Comment by leruge** [comment]
我是用nginx启动的web服务？应该用nginx还是swoole启动web服务呀？

**Comment by leruge** [comment]
我手动安装了一下think-swoole扩展，现在报错，走进tp框架了，应该有希望解决了。

**Comment by suanju** [comment]
很久之前写的了有问题可以加qq 2506152074
